language: node_js

node_js:
  - "8.12.0"

# 缓存“node_modules”目录
cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm hexo-cli

install:
  - npm install
  - cd ./themes/indigo1/
  - npm install

script:
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  github-token: ${personalAccessTokens}  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: "public"
  on:
    branch: master
